### PR TITLE
Design resources every developer need.

### PR DESCRIPTION
**Pull request by iamrajput**
# 🤔 This is a 
- [x] Feature
- [ ] Bug 
- [  ] Documentation Update
- [ ] Translation

# ✍ Description
- I Added a Useful Resources for the developers.

# Added to documentation
- [x] readme file
- [ ] No documentation needed

# 🐱‍💻 Use a meme/gif to describe how you feel for contributing (optional)

### CODE REVIEW

**Comment by muchirijane** [comment]
Hey, please read the contribution guidelines in the contribution.md file. Compare the pull request to the develop branch, write a short description, and check the checkboxes. 
I have included an example of how the pr template should be filled 👍🏽

**Comment by iamrajput** [comment]
There is one developer branch. i can't find any develop branch. Thanks

**Comment by muchirijane** [comment]
Yes, that's what you should compare it to instead of the main branch.

**Comment by muchirijane** [comment]
I have taken a look at the design resource repo, it's already under CSS resources. 
You can find another Github repo with resources that are not already included. 👍🏽

**Comment by iamrajput** [comment]
okay. no issue

**Pull request closed without merging**
