### PR TITLE
Adding words for improve the translation

### PR DESCRIPTION
**Pull request by MigueMartelo**
# 🤔 This is a 
- [ ] Feature
- [ ] Bug 
- [ ] Documentation Update
- [x] Translation

# ✍ Description
- Added spanish translation to Readme file.

# Added to documentation
- [ ] readme file
- [x] No documentation needed

# 🐱‍💻 Use a meme/gif to describe how you feel for contributing (optional)

### CODE REVIEW

**Comment by MigueMartelo** [comment]
I can't find the conflicts, can you help me?

**Comment by muchirijane** [comment]
Hey, let me take a look at it.

**Comment by MigueMartelo** [comment]
Thank you, tell me anything you find.

**Comment by MigueMartelo** [comment]
@muchirijane do yo have anything about this PR? For solve. I'm waiting 😃

**Comment by muchirijane** [comment]
I have checked it out, You are the one who can solve it from your repo. 

Step 1
git checkout -b MigueMartelo-feature/spanish-translation developer
git pull https://github.com/MigueMartelo/learning-code-through-github-repos.git feature/spanish-translation

Step 2
git checkout developer
git merge --no-ff MigueMartelo-feature/spanish-translation
git push origin developer

I hope that helps. Let me know if it doesn't.

**Comment by MigueMartelo** [comment]
I don´t know what happen, I made that you tell me and is the same conflict, help me please.

**Pull request merged**
